### ISSUE TITLE
Please assist with demo

### ISSUE THREAD

**Issue by geraldoluoch** [Root-vb/OTPFieldView#2]
Please assist with a suitable demo of this, tried following the guide on your site but it is not working at all.

**Comment by Root-vb** [comment]
@Gerald-Alpha Can you please share the code of view controller. 

Steps : 
1. ADD  `pod 'OTPFieldView'` in Podfile 
2. Run ` pod update`
3. Drag and drop an empty view and from **IDENTITY INSPECTOR** in Left pane and change its class from **UIView** to **OTPFieldView**.
4. Follow Readme and customize as per your requirements.

**Comment by geraldoluoch** [comment]
Here is my view controller


`import UIKit
import OTPFieldView

class OTPViewController: UIViewController, UITextFieldDelegate {

    @IBOutlet weak var otpTextFieldView: OTPFieldView!

    func setupOtpView() {
               self.otpTextFieldView.fieldsCount = 5
               self.otpTextFieldView.fieldBorderWidth = 2
               self.otpTextFieldView.defaultBorderColor = UIColor.black
               self.otpTextFieldView.filledBorderColor = UIColor.green
               self.otpTextFieldView.cursorColor = UIColor.red
               self.otpTextFieldView.displayType = .underlinedBottom
               self.otpTextFieldView.fieldSize = 40
               self.otpTextFieldView.separatorSpace = 8
               self.otpTextFieldView.shouldAllowIntermediateEditing = false
               self.otpTextFieldView.otpInputType = .numeric
               self.otpTextFieldView.delegate = self
              self.otpTextFieldView.initializeUI()

           }

    @IBAction func completeOTPBtn(_ sender: Any) {
        let storyBoard: UIStoryboard = UIStoryboard(name: "Login", bundle: nil)
        let PermissionNotifyViewController = storyBoard.instantiateViewController(withIdentifier: "PermissionNotify") as! PermissionNotifyViewController
        self.present(PermissionNotifyViewController, animated: true, completion: nil)

    }
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.

    }

}

    enum DisplayType: Int {
        case circular
        case roundedCorner
        case square
        case diamond
        case underlinedBottom
}

    extension OTPViewController: OTPFieldViewDelegate {
        func hasEnteredAllOTP(hasEnteredAll hasEntered: Bool) -> Bool {
            print("Has entered all OTP? \(hasEntered)")
            return false
        }

        func shouldBecomeFirstResponderForOTP(otpTextFieldIndex index: Int) -> Bool {
            return true
        }

        func enteredOTP(otp otpString: String) {
            print("OTPString: \(otpString)")
        }
    }


   

   /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destination.
       // Pass the selected object to the new view controller.
   }
    */`

**Comment by geraldoluoch** [comment]
Done all steps correctly as advised, but still not working

**Comment by Root-vb** [comment]
```
override func viewDidLoad() {
    super.viewDidLoad()

    // You forgot to add this.
    self.setupOtpView()
}
```
