### ISSUE TITLE
support for textContentType as oneTimeCode

### ISSUE THREAD

**Issue by anirudhamahale** [Root-vb/OTPFieldView#3]
Does your library supports autofilling of digits to respected position?
```swift
otptextField.textContentType = .oneTimeCode
```

**Comment by Root-vb** [comment]
@anirudhamahale No, Not yet.

**Comment by anirudhamahale** [comment]
Any future plans?

**Comment by Root-vb** [comment]
I'm Working on it. If you have anything that can help, please submit a PR. Any contribution is appreciated.

**Comment by Root-vb** [comment]
@anirudhamahale You can use this, .oneTimeCode is working now.
