### ISSUE TITLE
How to change font color?

### ISSUE THREAD

**Issue by satishVekariya** [Root-vb/OTPFieldView#4]

**Comment by Root-vb** [comment]
Haven't added that yet. Will add in next update. For now it'll be black only.

**Comment by vivekshah-zymr** [comment]
@Root-vb ,
Can we have this feature? Other background color and border colour change feature are not that useful if we can't change the font colour.

**Comment by AjazDev** [comment]
You can use this fork for now...
https://github.com/AjazDev/OTPFieldView
Already created a pull request... waiting for the merge with master.
