### ISSUE TITLE
Is there any way i can add a suggested code from keyboard to fill this all text fields.

### ISSUE THREAD

**Issue by ffahadMalikk** [Root-vb/OTPFieldView#5]
Hello, 
i have been trying to add the otp i got from a service and since iOS 12 its possible to show that sms otp into keyboard suggestion. so we can just tap that and otp field will be filled with provided data.

**Comment by Root-vb** [comment]
Hi @ffahadMalikk ,
If you're talking about OneTimeCode then, YES, you can achieve this by adding this to your code.

`otptextField.textContentType = .oneTimeCode`

**Comment by ffahadMalikk** [comment]
Hi @Root-vb thank you for your response. but actually i am asking for like auto fill password. As from iOS 12 apple allows you to read verification code from sms and show suggestion on keyboard and typing that will set the code. I want this to control manually like is there any kind of approach  using which i can set a string of 4 digits to fill the textfields in the view.

**Comment by Root-vb** [comment]
Hey @ffahadMalikk, If you add this to your code,

`otptextField.textContentType = .oneTimeCode` 

![qF1ud44](https://user-images.githubusercontent.com/22509106/74408075-70d0a800-4e59-11ea-9ee6-e41491011688.jpg)

Using this you can do exactly like the screenshot. Rest I didn't get your, 
> I want this to control manually 

part.

**Comment by ffahadMalikk** [comment]
I have a numeric string for 4 characters and i want to set that string to code view. My scenario consists of a case when i have a string from API and on tap of a button i want to fill the OTPview with that string.

**Comment by Root-vb** [comment]
@ffahadMalikk No, for now you can't. But that's something important that went unnoticed. I'll surely look into it soon. If you have anything that can help, please submit a PR. Any contribution is appreciated.

**Comment by ffahadMalikk** [comment]
Will do if i got any free time i send you a PR. Thank you!

**Comment by ffahadMalikk** [comment]
@Root-vb I have done resolved this issue with custom String input to text fields. i did not fork yet and not committed any changes. Is it ok if i do now?

**Comment by Root-vb** [comment]
@ffahadMalikk  If you have anything that can help, please submit a PR. Any contribution is appreciated.

**Comment by ffahadMalikk** [comment]
Sure will send you one shortly

**Comment by ffahadMalikk** [comment]
Hello Vaibhav,
As i mentioned earlier i have sent a PR and try to make sure to follow same
style you followed in previous commits.
Will look forward for your response.

Regards,
